services:
  - type: web
    name: stress_detection_ANN
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - fromFile: .env
    pythonVersion: 3.11.9
