services:
  - type: web
    name: stress-detection-ann
    env: python
    pythonVersion: 3.11.9
    # This tells Render to run commands from within your 'stress_detection' subfolder
    rootDir: stress_detection
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: "gunicorn stress_detection.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true # Render will automatically create a secure key
      - key: DEBUG
        value: False # Never run with Debug on in production
      - key: DATABASE_URL
        fromDatabase:
          name: stress_detection_db # <-- IMPORTANT: CHANGE THIS!
          property: internalUrl