services:
  - type: web
    name: stress_detection_ANN
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn stress_detection.wsgi:application
    pythonVersion: 3.11.9
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: stress_detection.settings
