# Generated by Django 5.0.3 on 2024-11-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StressParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snoring_rate', models.FloatField()),
                ('respiratory_rate', models.FloatField()),
                ('body_temperature', models.FloatField()),
                ('limb_movement', models.FloatField()),
                ('blood_oxygen', models.FloatField()),
                ('eye_movement', models.FloatField()),
                ('sleep_hours', models.FloatField()),
                ('heart_rate', models.FloatField()),
                ('stress_level', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
